export const SUCCESS_FETCH_MATERIALS = 'SUCCESS_FETCH_MATERIALS'
export const SUCCESS_FETCH_COLLECTION = 'SUCCESS_FETCH_COLLECTION'
export const SUCCESS_FETCH_SEASONS = 'SUCCESS_FETCH_SEASONS'
export const SUCCESS_FETCH_CLOTHES = 'SUCCESS_FETCH_CLOTHES'